# 启动命令
version: '3'
services:
  # redis-server
  breeze-redis:
    image: redis
    container_name: breeze-redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data/:/data
      - /etc/localtime:/etc/localtime:ro
    command:
      redis-server /etc/redis/redis.conf
    networks:
      - breeze-net

  # 数据库5.7版本
  breeze-mysql:
    image: mysql:5.7
    container_name: breeze-mysql
    restart: always
    environment:
      MYSQL_DATABASE: breeze_test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /usr/local/soft/docker-env-dev/mysql/db/breeze_config.sql /docker-entrypoint-initdb.d/
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/logs/:/var/log
      - /etc/localtime:/etc/localtime:ro
    networks:
      - breeze-net

  breeze-nacos:
    image: nacos/nacos-server:2.0.1
    container_name: breeze-nacos
    restart: always
    depends_on:
      - breeze-mysql
    environment:
      # PREFER_HOST_MODE: hostname #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      SPRING_DATASOURCE_PLATFORM: mysql
      MODE: standalone
      MYSQL_SERVICE_HOST: breeze-mysql
      MYSQL_SERVICE_DB_NAME: breeze_config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      NACOS_APPLICATION_PORT: 8848
      JVM_XMS: 512m
      JVM_MMS: 320m
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
      - ./nacos/plugins/:/home/nacos/plugins
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8848:8848"
    networks:
      - breeze-net

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - breeze-nacos
    restart: on-failure
    networks:
      - breeze-net

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - breeze-net

  breeze-sentinel-dashboard:
    container_name: breeze-sentinel-dashboard
    image: breezeworker/breeze-sentinel-dashboard:1.8.3
    ports:
      - "8080:8080"
    environment:
      NACOS_HOST: breeze-nacos
      NACOS_PORT: 8848
      USERNAME: admin
      PASSWORD: admin
    depends_on:
      - breeze-nacos
    restart: on-failure
    networks:
      - breeze-net

  # seata服务1
  breeze-seata-server-1:
    image: seataio/seata-server:latest
    container_name: breeze-seata-server-1
    hostname: breeze-seata-server
    ports:
      - "8091:8091"
    environment:
      # 指定 seata 服务启动端口
      - SEATA_PORT=8091
      # 注册到 nacos 上的ip。客户端将通过该ip访问seata服务。
      # 注意公网ip和内网ip的差异。
      - SEATA_IP=127.0.0.1
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      # 因为registry.conf中是nacos配置中心，只需要把registry.conf放到./seata-server/config文件夹中
      - "./seata-server/config:/root/seata-config"
    networks:
      - breeze-net

  # seata服务2
  breeze-seata-server-2:
    image: seataio/seata-server:latest
    container_name: breeze-seata-server-2
    hostname: breeze-seata-server
    ports:
      - "8092:8092"
    environment:
      # 指定seata服务启动端口
      - SEATA_PORT=8092
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务。
      # 注意公网ip和内网ip的差异。
      - SEATA_IP=127.0.0.1
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      # 因为registry.conf中是nacos配置中心，只需要把registry.conf放到./seata-server/config文件夹中
      - "./seata-server/config:/root/seata-config"
    networks:
      - breeze-net

  # java程序
  breeze-boot:
    container_name: breeze-boot
    image: breeze-app
    build:
      context: .
      dockerfile: ./java/breeze-boot.dockerfile
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      BREEZE_REDIS_HOST: breeze-redis
      BREEZE_REDIS_PORT: 6379
      BREEZE_REDIS_PASSWORD: breeze
      BREEZE_MYSQL_HOST: breeze-mysql
      BREEZE_MYSQL_PORT: 3306
      BREEZE_MYSQL_DB_NAME: breeze_admin
      BREEZE_MYSQL_USERNAME: root
      BREEZE_MYSQL_PASSWORD: root
    volumes:
      - ./java/breeze-boot/logs:/usr/local/breeze/logs
      - ./java/breeze-boot/upload:/usr/local/breeze/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - breeze-redis
      - breeze-mysql
    links:
      - breeze-redis
      - breeze-mysql
    networks:
      - breeze-net

  # nginx
  breeze-nginx:
    container_name: breeze-nginx
    image: nginx:1.16
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx/html/breeze-web:/usr/local/nginx/html/breeze-web
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - breeze-boot
    links:
      - breeze-boot
    networks:
      - breeze-net

networks:
  breeze-net:
    # 如果要创建外部隔离的覆盖网络，您可以将此internal选项设置为true
    external: false
